### ISSUE TITLE
Hashrate bugs

### ISSUE THREAD

**Issue by smiba** [MrLuit/GarlicPoolOrgBot#2]
Due some error in the pool's code it can happen that after finding a block the hashrate suddenly doubles in the calculation.

I would suggest to store the last received MH/s in memory and then if on the next refresh it has increased with more then 30% compared to the previous result to ignore the update for then.

Basicly:
1. Refresh pool hashspeed
2. Compare to last received pool hashspeed from memory
3. If the hashspeed has not increased by more then 30% since the last refresh update discord
4. Store result in memory (Even if it was too high and discord didn't update!)
5. Return to start

I do not know enough about JS to do this well, other then some glued together code. Maybe someone else can? Thanks

**Comment by Baizey** [comment]
should be fixed with commit fa0e184a46c60886a6362a64d363a3b3586f3e24
